version: '2'
services:
  web:
    build: .
    command: bash runserver.sh
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - anno-db:/data/db

volumes:
  anno-db:
    external: true
